In [2]:
import numpy as np

In [13]:
a = np.array([1,2,3,4,5],dtype = "int16")
a

array([1, 2, 3, 4, 5], dtype=int16)

In [6]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(a.ndim)
print(b.ndim)

1
2


In [10]:
print(a.shape)
b.shape

(5,)


(2, 3)

In [14]:
a.dtype

dtype('int16')

In [17]:
print(a.itemsize)
print(b.itemsize)

2
8


In [20]:
a.nbytes
#2 bytes for each element in a(number of elements in a = 5) giving an answer of 10 bytes (2*5)

10

In [28]:
a = np.array([[1, 2, 3, 4, 5,6,7],[8, 9, 10, 11, 12, 13, 14],[15, 16, 17, 18, 19, 20, 21]])

In [23]:
a[0,2::2]

array([3, 5, 7])

In [30]:
a[:,2:3]

array([[ 3],
       [10],
       [17]])

In [36]:
b = np.array(
    [
        [
            [1, 2, 3, 4, 5, 6, 7],
            [8, 9, 10, 11, 12, 13, 14],
            [30, 31, 32, 33, 34, 35, 36]
        ],
        [
            [15, 16, 17, 18, 19, 20, 21], 
            [22, 23, 24, 25, 26, 27, 28], 
            [29, 30, 31, 32, 33, 34, 35]
        ]
    ]
    )

In [37]:
b

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [30, 31, 32, 33, 34, 35, 36]],

       [[15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28],
        [29, 30, 31, 32, 33, 34, 35]]])

In [40]:
b[1,2,1:]

array([30, 31, 32, 33, 34, 35])

## initializing some arrays

In [44]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
np.full((2,4),43)

array([[43, 43, 43, 43],
       [43, 43, 43, 43]])

In [47]:
np.full_like(b,4)

array([[[4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4]],

       [[4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4]]])

In [48]:
np.random.rand(4,3)

array([[0.4013228 , 0.37825645, 0.76225785],
       [0.62819168, 0.40429777, 0.94091685],
       [0.50258228, 0.99291094, 0.15821396],
       [0.45224435, 0.66063519, 0.1888854 ]])

In [50]:
np.random.randint(4 ,32,size = (3,6))

array([[ 5, 10, 21, 17, 19, 30],
       [20, 17, 27, 24, 18, 25],
       [10, 10, 11, 23, 14, 23]], dtype=int32)

In [51]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
aa = np.array([[1,2,3]])
r1 = np.repeat(aa,4,axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [62]:
test =np.ones((5,5))
test[1:4,1:4] = 0
test [2,2] = 9
test

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

OR

In [64]:
test =np.ones((5,5))
z = np.zeros((3,3))
z [2,2] = 9
test[1:4,1:4] = z
test

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 9., 1.],
       [1., 1., 1., 1., 1.]])

copy an array
\

In [72]:
test2 = test.copy()
test2 = np.ones(test.shape)
print(test2)
test

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 9., 1.],
       [1., 1., 1., 1., 1.]])

mathematic

In [83]:
print(b)
b = b+2
print(b)
b-=2
print(b)
print(b*2)
print(b/2)
b

[[[ 3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16]
  [32 33 34 35 36 37 38]]

 [[17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37]]]
[[[ 5  6  7  8  9 10 11]
  [12 13 14 15 16 17 18]
  [34 35 36 37 38 39 40]]

 [[19 20 21 22 23 24 25]
  [26 27 28 29 30 31 32]
  [33 34 35 36 37 38 39]]]
[[[ 3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16]
  [32 33 34 35 36 37 38]]

 [[17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37]]]
[[[ 6  8 10 12 14 16 18]
  [20 22 24 26 28 30 32]
  [64 66 68 70 72 74 76]]

 [[34 36 38 40 42 44 46]
  [48 50 52 54 56 58 60]
  [62 64 66 68 70 72 74]]]
[[[ 1.5  2.   2.5  3.   3.5  4.   4.5]
  [ 5.   5.5  6.   6.5  7.   7.5  8. ]
  [16.  16.5 17.  17.5 18.  18.5 19. ]]

 [[ 8.5  9.   9.5 10.  10.5 11.  11.5]
  [12.  12.5 13.  13.5 14.  14.5 15. ]
  [15.5 16.  16.5 17.  17.5 18.  18.5]]]


array([[[ 3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16],
        [32, 33, 34, 35, 36, 37, 38]],

       [[17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37]]])

In [94]:
test = np.sin(test)

In [86]:
test + test

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  0.,  0.,  0.,  2.],
       [ 2.,  0.,  0.,  0.,  2.],
       [ 2.,  0.,  0., 18.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

linear algera


In [88]:
m = np.ones((2,3))
print(m)
n = np.full((3,2),2)
print(n)

np.matmul(m,n)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [93]:
q =np.identity(6)
np.linalg.det(q)


np.float64(1.0)

In [97]:
print(np.min(test))
print(np.max(test))
print(np.sum(test))
print()

0.0
0.8414709848078965
13.875654242168102



reorganizing

In [99]:
before = np.array([1,2,3,4,5])
after = before.reshape(5,1)
after

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [109]:
v1 = np.array([1,2,3,4,5])
v2 =np.array([8,9,10,11,12])

np.vstack((v1,v2,v1))

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5]])

In [108]:
v1 = np.array([1,2,3,4,5])
v2 =np.array([8,9,10,11,12])

np.hstack((v1,v2,v1))

array([ 1,  2,  3,  4,  5,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5])

In [110]:
b*=5

In [111]:
b > 50

array([[[False, False, False, False, False, False, False],
        [False,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True]]])

In [112]:
b[b>50]

array([ 55,  60,  65,  70,  75,  80, 160, 165, 170, 175, 180, 185, 190,
        85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145,
       150, 155, 160, 165, 170, 175, 180, 185])

In [128]:
b[(b > 50) & (b < 100)]

array([55, 60, 65, 70, 75, 80, 85, 90, 95])